apiVersion: v1
kind: Pod
metadata:
  name: hello-world-app
  labels:
    app.kubernetes.io/name: helloworld
spec:
  containers:
  - name: hello-world-app
    image: heiderhengstmann/javaapps:helloworld-v1.1
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: helloworld
  ports:
  - name: hello-world-service-port
    protocol: TCP
    port: 80
    targetPort: 8181






























